### ISSUE TITLE
Metrics visualization development

### ISSUE THREAD

**Issue by aebudden** [DataONEorg/community-engagement-outreach#11]
For use in newsletter (#1), web updates, 2-pager (#2), etc.

**Comment by meg3mach** [comment]
Metrics updates that can't be automated (i.e., education, users, trainings...) https://docs.google.com/spreadsheets/d/1wqKAh2tX9cgGqxbN_mAIrj3xAP8pLu5zNzMxmrtOIys/edit?usp=sharing

**Comment by meg3mach** [comment]
In the metrics datasheet I created a new worksheet called “OutreachMetrics_…” 
We now need to evaluate which of the metrics we picked as" valuable for outreach" from the full list of 150 should be added to "by the numbers" for the newsletter (and later the web).

On that sheet, column “S” is what we want to include in the newsletter. I’m having a hard time adding checks to this column because I can’t really evaluate how easy it is to get some of these values. It would help me if you (Amber) could take a look and add some x's. 

https://docs.google.com/spreadsheets/d/1mTtm3FMmXP1vZDvVC1wsOGb5GK1H4-aB_4jgce6mX-Q/edit#gid=1893867262

**Comment by meg3mach** [comment]
@aebudden, I have added a new worksheet to the DataONE metrics spreadsheet for those that we have to gather by hand. For now it only contains those we need for the newsletter and 2-pager.

https://docs.google.com/spreadsheets/d/1mTtm3FMmXP1vZDvVC1wsOGb5GK1H4-aB_4jgce6mX-Q/edit#gid=1893867262

The worksheet is called "Quarterly Metrics Update - ..."

There are a few blanks under the webinars, the uptime, people trained, data contributors (if we are keeping this) and search events. I'm going to msg Dave about uptime and search events.

<b>Your TODOs:</b>
- [ ]  Share our webinar metrics datasheet with attendance and viewing stats. Can I check the Vimeo attendance counts myself?
 Here's the webinar metrics folder: https://drive.google.com/drive/folders/0B45VEFp1GugSfi1oZWhiUGZqUGlyX0RqaS1VQnFEV3hWVl9wbXVfMFpSNWEtMG5WamY5dWs?usp=sharing
- [ ] Check to see if People Trained has changed
- [ ] Decide whether data contributors is worth pursuing, and who I need to pursue to get these values.

**Comment by aebudden** [comment]
Updated webinar metrics: https://drive.google.com/drive/folders/0B45VEFp1GugSfi1oZWhiUGZqUGlyX0RqaS1VQnFEV3hWVl9wbXVfMFpSNWEtMG5WamY5dWs. Yes, you can log in to vimeo and see those numbers. Login is my unm email and I'll slack the pwd.

**Comment by aebudden** [comment]
Data contributors would come from CI. I don't know if there's a place that you can pull that number or if it will be an ask each quarter. @datadavev?

**Comment by meg3mach** [comment]
Here is a first draft of "... by the numbers" https://drive.google.com/file/d/154sk1emhL2bjS-U0M1qlBpwNpSfEkDio/view?usp=sharing

**Comment by meg3mach** [comment]
Updated draft of By the Number - https://drive.google.com/file/d/154sk1emhL2bjS-U0M1qlBpwNpSfEkDio/view?usp=sharing

**Comment by aebudden** [comment]
Metrics activity for newsletter complete. Updating ticket to reflect activity preparing for web based metrics in advance of AHM. Metrics worksheet located at: https://docs.google.com/spreadsheets/d/1U6B8sa1tjGRXPEAbQHRLYtt7C_visUvVW4u7hxmRXQo/edit#gid=0
