### ISSUE TITLE
Square DataONE Logo

### ISSUE THREAD

**Issue by aebudden** [DataONEorg/community-engagement-outreach#13]

**Comment by meg3mach** [comment]
Square logos can all be found in this folder: https://drive.google.com/drive/folders/13eOOsUDUP6_76UwPwpDMqt8ounkGRjiW?usp=sharing

**Comment by csjx** [comment]
Heya @aebudden @meg3mach - These square logos look great - I like the node and connector design 👍 .  It would be awesome if the original vector files are committed into this github repo so they can be scaled for different uses. SVG, PDF-A with editable layers, or AI formats would be great. 🙂

**Comment by aebudden** [comment]
Glad you like them. Once we get the sign off from the LT originals can be added with guidelines on usage. Keeping them in team access Gdrive until finalized.

**Comment by aebudden** [comment]
Request to get feedback form the community.  Create a mock up twitter feed at the size it would render using the network, split DataONE and globe versions of the square logo.

**Comment by meg3mach** [comment]
Mockups of Twitter and Facebook with DataONE square logo. With twitter we should keep the globe because we are forced to have a round logo. It looks way better than the square. With facebook I could go either way, but the split is easier to read. 
https://drive.google.com/drive/folders/13eOOsUDUP6_76UwPwpDMqt8ounkGRjiW

**Comment by aebudden** [comment]
Added a quick a dirty v2 for twitter - we need to see the logo at scale as part of the twitter feed.

**Comment by meg3mach** [comment]
The circle on twitter is the best.
